services:
  database:
    env_file:
      - .env.staging
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  api:
    image: ghcr.io/miichaaeell/desafio_lacrei_saude/desafio-lacrei-api:latest
    env_file:
      - .env.staging
    ports:
      - "8010:8000"

volumes:
  postgres_data:
    name: desafio_lacrei_postgres_staging
