services:
  api:
    image: ghcr.io/miichaaeell/desafio_lacrei_saude/desafio-lacrei-api:latest
    ports:
      - "8020:8000"
    env_file:
      - .env.prod

volumes:
  postgres_data:
    name: desafio_lacrei_postgres_prod
